name: repeat_notification_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  flutter_timezone: ^1.0.8
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  material_color_utilities:
  path_provider:
  riverpod_annotation: ^2.3.3
  roggle: ^0.4.2+1
  timezone:

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  isar_generator: 3.1.0+1
  pedantic_mono: ^1.25.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

dependency_overrides:
  # isarが<6.0.0、riverpod_lintが>=6.0.0を要求しているため、isarのバージョンを上書き
  analyzer: ^6.2.0

flutter:
  uses-material-design: true
